In [1]:
# Step 1: Import Required Library
# This step imports the pandas library to work with DataFrames.
import pandas as pd

In [2]:
# Step 2: Create the Student DataFrame
# This step creates a pandas DataFrame using the provided student data.
data = {
    "StudentID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Alice","Bob","Charlie","Diana","Ethan","Fiona","George","Hannah","Ivan","Julia"],
    "Age": [20,21,19,22,20,21,23,19,22,20],
    "Marks": [88,75,92,65,78,85,70,95,60,80],
    "Grade": ["A","B","A","C","B","A","B","A","C","B"]
}

df = pd.DataFrame(data)
df

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

In [3]:
# Step 3: Save the DataFrame as CSV
# This step saves the DataFrame as a CSV file named students.csv.

df.to_csv("students.csv", index=False)

In [4]:
# Step 4: Reload the CSV into a New DataFrame
# This step reloads the saved CSV file into a new DataFrame.

df_new = pd.read_csv("students.csv")
df_new

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

In [5]:
# Step 5: Display First 3 Rows
# This step displays the first 3 rows of the DataFrame.

df_new.head(3)

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A

In [6]:
# Step 6: Display Statistical Summary
# This step shows statistical summary of numerical columns.

df_new.describe()

       StudentID        Age      Marks
count   10.00000  10.000000  10.000000
mean   105.50000  20.700000  78.800000
std      3.02765   1.337494  11.535453
min    101.00000  19.000000  60.000000
25%    103.25000  20.000000  71.250000
50%    105.50000  20.500000  79.000000
75%    107.75000  21.750000  87.250000
max    110.00000  23.000000  95.000000

In [7]:
# Step 7: Explore Data Further
# This step shows number of rows and columns.

df_new.shape

(10, 5)

In [8]:
# Display Data Types
# This step shows data types of each column.

df_new.dtypes

StudentID     int64
Name         object
Age           int64
Marks         int64
Grade        object
dtype: object

In [9]:
# Display Complete Info
# This step shows detailed information including non-null counts.

df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     int64
 1   Name       10 non-null     object
 2   Age        10 non-null     int64
 3   Marks      10 non-null     int64
 4   Grade      10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

Student DataFrame Creation and Exploration using Pandas

In this notebook, I created a Student DataFrame using pandas with the provided dataset. The DataFrame was saved as a CSV file (students.csv) and then reloaded into a new DataFrame. Various DataFrame exploration techniques such as head(), describe(), shape, dtypes, and info() were used to analyze and understand the structure, statistics, and data types of the dataset.